# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test2023',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nbdev-test2023',
                'lib_path': 'nbdev_test2023'},
  'syms': {'nbdev_test2023.core': {'nbdev_test2023.core.foo': ('core.html#foo', 'nbdev_test2023/core.py')}}}
